import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { GenerateResult } from "./types.js";
import { toSnakeCase } from "./naming.js";

function packageName(serverName: string): string {
  return toSnakeCase(serverName).replace(/_/g, "-");
}

function buildToolFile(tool: GenerateResult["tools"][number]): string {
  const shapeEntries = Object.entries(tool.zodShape)
    .map(([key, value]) => `  ${key}: ${value},`)
    .join("\n");
  const typeEntries = Object.entries(tool.argsType)
    .map(([key, value]) => `${key}: ${value};`)
    .join(" ");
  const imports = ['import { z } from "zod";', ...tool.imports].join("\n");

  return `${imports}

export const name = ${JSON.stringify(tool.toolName)};
export const description = ${JSON.stringify(tool.description)};

export const schema = {
${shapeEntries}
};

export async function handler(args: { ${typeEntries} }) {
  ${tool.handlerBody}
}
`;
}

function buildIndexFile(result: GenerateResult): string {
  const imports = result.tools
    .map((tool) => `import * as ${tool.fileBaseName} from "./tools/${tool.fileBaseName}.js";`)
    .join("\n");
  const registrations = result.tools
    .map(
      (tool) =>
        `server.registerTool(${tool.fileBaseName}.name, { description: ${tool.fileBaseName}.description, inputSchema: ${tool.fileBaseName}.schema }, ${tool.fileBaseName}.handler);`,
    )
    .join("\n");

  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
${imports}

const server = new McpServer({ name: ${JSON.stringify(packageName(result.serverName))}, version: "0.1.0" });

${registrations}

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

function buildPackageJson(result: GenerateResult): string {
  const pkg = {
    name: packageName(result.serverName),
    version: "0.1.0",
    description: `MCP server generated by ai-to-mcp from ${result.mode === "openapi" ? "an OpenAPI spec" : "TypeScript functions"}.`,
    type: "module",
    bin: {
      [packageName(result.serverName)]: "./dist/index.js",
    },
    scripts: {
      build: "tsc",
      start: "node dist/index.js",
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.30.0",
      zod: "^4.0.0",
    },
    devDependencies: {
      "@types/node": "^22.10.5",
      typescript: "^5.7.3",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

function buildTsconfig(): string {
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      outDir: "dist",
      rootDir: "src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
    },
    include: ["src"],
  };
  return `${JSON.stringify(tsconfig, null, 2)}\n`;
}

function buildReadme(result: GenerateResult): string {
  const toolList = result.tools.map((tool) => `- \`${tool.toolName}\`: ${tool.description}`).join("\n");

  const authSection =
    result.mode === "openapi"
      ? [
          "",
          "## configuration",
          "",
          `the base url is set to \`${result.baseUrl}\`. override it with the \`API_BASE_URL\` environment variable if you need to point somewhere else.`,
          "",
          authEnvDescription(result.auth?.kind),
        ].join("\n")
      : "";

  const warningsSection =
    result.warnings.length > 0 ? `\n## notes\n\n${result.warnings.map((w) => `- ${w}`).join("\n")}\n` : "";

  return `# ${packageName(result.serverName)}

an mcp server generated by [ai-to-mcp](https://github.com/TheCEO3-rgb/ai-to-mcp).

## install

\`\`\`bash
npm install
npm run build
\`\`\`

## run

\`\`\`bash
node dist/index.js
\`\`\`

this server speaks mcp over stdio, so it's meant to be launched by an mcp client (claude desktop, claude code, or any other mcp-compatible tool), not run directly on its own.
${authSection}
## tools

${toolList}
${warningsSection}`;
}

function authEnvDescription(kind: string | undefined): string {
  switch (kind) {
    case "bearer":
      return "set `API_TOKEN` to a bearer token for apis that need authentication.";
    case "apiKeyHeader":
      return "set `API_KEY` to your api key. it gets sent as a request header.";
    case "apiKeyQuery":
      return "set `API_KEY` to your api key. it gets sent as a query parameter.";
    default:
      return "this api didn't declare a supported auth scheme, so no authentication is wired in. add it yourself in `src/client.ts` if the api needs it.";
  }
}

export async function writeGeneratedServer(result: GenerateResult, outDir: string): Promise<void> {
  await mkdir(join(outDir, "src", "tools"), { recursive: true });

  await writeFile(join(outDir, "package.json"), buildPackageJson(result));
  await writeFile(join(outDir, "tsconfig.json"), buildTsconfig());
  await writeFile(join(outDir, "README.md"), buildReadme(result));
  await writeFile(join(outDir, "src", "index.ts"), buildIndexFile(result));

  if (result.clientFileCode) {
    await writeFile(join(outDir, "src", "client.ts"), result.clientFileCode.trimStart());
  }

  for (const tool of result.tools) {
    await writeFile(join(outDir, "src", "tools", `${tool.fileBaseName}.ts`), buildToolFile(tool));
  }

  for (const sourceFile of result.sourceFiles ?? []) {
    const fullPath = join(outDir, "src", "source", sourceFile.relativePath);
    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, sourceFile.code);
  }

  const gitignore = "node_modules\ndist\n*.log\n";
  await writeFile(join(outDir, ".gitignore"), gitignore);
}
